#!/bin/bash

#SBATCH -J final_coordination_1000
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err
#SBATCH -p normal
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 46:30:00
#SBATCH --mail-user=ashutosh.shukla@utexas.edu
#SBATCH --mail-type=all
#SBATCH -A Extreme-Weather-Even

# setup
# module load python3/3.7.0

# enter the repo directory
cd ${HOME}/ThreeStageModel

#run the python script
python3 main_notebook.py --run_name final_coordination_1000\
                         --machine tacc\
                         --mip_gap 0.005\
                         --time_limit 165600\
                         --max_prep 12\
                         --mip_focus 3\
                         --voll 1000\
                         --coordination yes\
                         #--initial_sol_path /work2/07346/ashukla/ls6/ThreeStageModel/output/modified_td_voll_500/solution.sol\