#!/bin/bash

#SBATCH -J modified_td_prep_0

#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err
#SBATCH -p skx-normal
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 36:30:00
#SBATCH --mail-user=ashutosh.shukla@utexas.edu
#SBATCH --mail-type=all
#SBATCH -A Extreme-Weather-Even

# setup
# module load python3/3.7.0

# enter the repo directory
cd ${HOME}/ThreeStageModel

# run the python script
python3 main_notebook.py --run_name modified_td_prep_0_1\
                         --machine tacc\
                         --mip_gap 0.005\
                         --time_limit 129600\
                         --first_stage_binary true\
                         --max_prep 0\
                         --prep_level 0\
                         --td_cost 40000\
                         --operating_cost 10000\
                         --mip_focus 3\
                         #--initial_sol_path /work2/07346/ashukla/stampede2/ThreeStageModel/output/modified_td_prep_18/solution.sol\
