#!/bin/bash
#SBATCH -J granular_perfect_prediction
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err
#SBATCH -p normal
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 46:30:00
#SBATCH --mail-user=ashutosh.shukla@utexas.edu
#SBATCH --mail-type=all
#SBATCH -A Extreme-Weather-Even

# setup
# module load python3/3.7.0

# enter the repo directory
cd ${HOME}/ThreeStageModel

#run the python script
python3 main_notebook.py --run_name granular_perfect_prediction\
                         --machine tacc\
                         --mip_gap 0.005\
                         --time_limit 165600\
                         --first_stage_binary false\
                         --mip_focus 3\
                         --voll 6000\
                         --max_mit 21\
                         --mit_level 3\
                         --max_prep 6\
                         --prep_level 3