#!/bin/bash

#SBATCH -J heuristic_3000
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err
#SBATCH -p normal
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 5:30:00
#SBATCH --mail-user=ashutosh.shukla@utexas.edu
#SBATCH --mail-type=all
#SBATCH -A Extreme-Weather-Even

# setup
# module load python3/3.7.0

# enter the repo directory
cd ${HOME}/ThreeStageModel

#run the python script
python3 heuristic_testing.py --run_name heuristic_3000\
                         --machine tacc\
                         --mip_gap 0.005\
                         --time_limit 18000\
                         --first_stage_binary true\
                         --voll 3000\
                         --td_cost 40000\
                         --operating_cost 10000